### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Exerciz** [u1qqlv/SURVIV.IO-PRO-HACK#2]
Edit: Everything fine.

**Comment by u1qqlv** [comment]
Can you show proof auto aim is bad because I think is the best...
https://www.youtube.com/watch?v=oOJxmHsRqSU
No menu this is custom hack for me, I don't need menu...
Trigger Bot is bad because it will attract a lot of attention, not like this. And I need a lot time to add new feautures - time I don't have, I think It will remain as it is. 
You can select keybind and use "Q" key to switch guns in game menu.
